[RU] Translations/Fixes
Timwi/KtaneContent pull request #1216
Opened 2022-01-25 23:54 UTC by Ethepi

The _actual_ PR should start from Jan 16, but for some reason it decided to attach previous PR commits.
- Translated: The Swan, Divided Squares, FMZ(& interactive).
- Fixed FMN typo
- Updated old [RU] manuals (refer to [this commit](https://github.com/Ethepi/KtaneContent/commit/160d1304bcc38432301a5b66236c33d8233b0692) for changes)

2022-01-26 10:53 UTC, nicklatkovich requested changes

2022-01-26 10:53 UTC, nicklatkovich commented on HTML/Divided Squares translated (Русский — Делённые Квадраты) (PoisonGreen).html
> +                <p>Если другой модуль был обезврежен до обезвреживания Делёных Квадратов, тогда квадрат может разделиться на 4 квадрата по меньше(9, и так далее). Один из этих квадратов является прав
* `поменьше`
* добавить пробел перед скобками
* есть ли причина почему используются количество квадратов, а не размер сетки (как это описано в оригинальном мануале)?

2022-01-26 10:53 UTC, nicklatkovich commented on HTML/Divided Squares translated (Русский — Делённые Квадраты) (PoisonGreen).html
> +                </div>
неверный отступ

2022-01-26 10:53 UTC, nicklatkovich commented on HTML/The Swan translated (Русский — Лебедь) (PoisonGreen).html
> +                    <li>Если количесто сбросов помноженное на 8 находится между двумя любыми числами из Биноминальной Спирали Радзинского — введите HATCH.</li>
Здесь перевод неверный. Количество сбросов помноженное на 8 должно находится в пределах двух от любого числа в биномиальной спирали.

2022-01-26 11:23 UTC, Ethepi commented on HTML/Divided Squares translated (Русский — Делённые Квадраты) (PoisonGreen).html
> +                <p>Если другой модуль был обезврежен до обезвреживания Делёных Квадратов, тогда квадрат может разделиться на 4 квадрата по меньше(9, и так далее). Один из этих квадратов является прав
1)Опечатка (забавно что она осталась, я файл прогонял через проверку орфографии)
2)Тоже опечатка
3)Хотел предложение по меньше сделать, чёт ничего иного не придумал. Как тогда такой вариант:
<p>Если другой модуль был обезврежен до обезвреживания Делёных Квадратов, тогда квадрат может разделиться в сетку квадратов 2 на 2 (3 на 3, и так далее). Один из этих квадратов является правильным, все остальные зачтут ошибку при взаимодействии.</p> ?

2022-01-26 11:24 UTC, Ethepi commented on HTML/Divided Squares translated (Русский — Делённые Квадраты) (PoisonGreen).html
> +                </div>
Какой отступ? Я вроде табуляцию не менял.

2022-01-26 11:55 UTC, nicklatkovich approved these changes

2022-03-03 02:17 UTC, Luminoscity commented
Thanks for your work on this, both of you. I'll review the linting for each of these files tonight. Please try to keep these requests to a smaller number of changed files in the future and we will get to them sooner.

2022-03-03 09:54 UTC, merged