add "UraMasyu" module's manual, PDF, and json
Timwi/KtaneContent pull request #1324
Opened 2023-03-08 03:47 UTC by YY-otter

2023-03-08 10:53 UTC, Luminoscity requested changes
embedded diagrams for translatability
fix linting errors (in the future, make sure you are checking with a DM to Logbot that your HTML files pass linting)
fixed formatting issues
add button that makes the page readable
delete duplicate SVG
PDFs are automatically generated and should not be included
fixed JSON errors

2023-03-08 10:53 UTC, Luminoscity commented on HTML/UraMasyu translated (日本語 — 裏ましゅ) (Y.Y.).html
> +                    <text transform="translate(1757 2994.68)"><tspan x="0" y="0" class="st5">No small loops (top left),</tspan><tspan x="0" y="52.8" class="st5">spurrs (bottom left), or</tspan><tspan
Making an imported SVG with lots of text that has been converted to <path> is not acceptable as it cannot be translated easily, and such path conversions take up hundreds more kilobytes than pure text. So I converted your diagrams to be embedded in the HTML and have actual text. Now you just have to type in the Japanese text you want here.

2023-03-10 04:28 UTC, YY-otter commented
The UraMasyu module has been updated to align with this content.

2023-03-10 15:51 UTC, merged

2023-03-10 15:51 UTC, Luminoscity commented
Next time, you don't need to keep pushing merge commits to your fork.
Now that it is merged, please rebase your fork to the latest so future pull requests won't have past commits in them.
Nice job on this mod.