Add The Console, update Identifying Soulless and Assembly Code
Timwi/KtaneContent pull request #753
Opened 2020-08-25 20:38 UTC by Burniel123

All files added for The Console, new version of Assembly Code (with table instead of image) added and svg minified (was not previously), added new songs to Identifying Soulless, icon for M&Ms, source link for Colored Buttons.

2020-08-25 22:28 UTC, sleepin-fang requested changes
Please review this closed PR for requested changes https://github.com/Timwi/KtaneContent/pull/751

2020-08-27 14:07 UTC, Burniel123 commented
Didn't realise anyone had made a start on these. Should have fixed everything flagged in the old PR now.

2020-08-27 14:54 UTC, sleepin-fang commented on HTML/Assembly Code.html
> +                    <tr></tr>
th are within tr

2020-08-27 23:01 UTC, sleepin-fang approved these changes

2020-08-27 23:01 UTC, merged