Add Quick Time Events.
Timwi/KtaneContent pull request #794
Opened 2020-10-12 12:34 UTC by Mirage-Xel

2020-10-12 16:48 UTC, Rdzanuwu commented on HTML/Quick Time Events.html
> +    <link rel="stylesheet" type="text/css" href="css/font.css">
Font before normalize.

2020-10-12 16:52 UTC, Rdzanuwu requested changes

2020-10-12 16:52 UTC, Rdzanuwu commented on HTML/Quick Time Events.html
> +            <div class="page-footer relative-footer">Page 1 of 2</div>
I guess this wasn't supposed to be Page 1 of 2.

2020-10-14 02:35 UTC, samfundev commented
Merged in 619b68d8e80f07b42dd8015cd3d49c56ce7bdb55

2020-10-14 02:35 UTC, closed without merging