Baybayin Words, Pixel Number Base JSON Spelling Fixes
Timwi/KtaneContent pull request #809
Opened 2020-10-30 14:35 UTC by Mirage-Xel

2020-11-02 17:46 UTC, MrPeanut1028 commented on HTML/Baybayin Words.html
> +               <tr><td>kayumanggi</td><td>brown</td><td>lipad</td><td>fly</td><td>kutsilyo</td><td>knife</td></tr>
Perhaps fix these two lines that aren't with the others.

2020-11-02 17:48 UTC, MrPeanut1028 commented on HTML/img/Component/Baybayin Words.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
You'll need to put this file through [SVG minification](https://jakearchibald.github.io/svgomg/).

2020-11-02 17:49 UTC, MrPeanut1028 commented on JSON/Baybayin Words.json
> +  "Author": "Panoptes (Xel), CrunchyBot",
Remove either the Authors or the Contributors section, you do not need both.

2020-11-02 17:52 UTC, MrPeanut1028 commented on JSON/Pixel Number Base.json
> -  "Author": "Panoptes (Xel), Crunchybot",
Just checked the repo. It doesn't actually display it twice but it does show a little `?` when you hover, which isn't supposed to happen. If you could remove this line, that would be great.

2020-11-02 18:50 UTC, samfundev requested changes

2020-11-02 18:50 UTC, samfundev commented on HTML/Baybayin Words.html
> +    <link rel="stylesheet" type="text/css" href="css/font.css">
```suggestion
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1">
    <title>Baybayin Words — Keep Talking and Nobody Explodes Module</title>
    <link rel="stylesheet" type="text/css" href="css/font.css">
    <link rel="stylesheet" type="text/css" href="css/normalize.css">
    <link rel="stylesheet" type="text/css" href="css/main.css">
```

2020-11-02 18:50 UTC, samfundev commented on HTML/Baybayin Words.html
> +			   <tr> <td>Word</td><td>Translation</td><td>Word</td><td>Translation</td><td>Word</td><td>Translation</td></tr>
```suggestion
               <table>
               <tr><td colspan="6"><strong>Translation Table</strong></td></tr>
               <tr> <td>Word</td><td>Translation</td><td>Word</td><td>Translation</td><td>Word</td><td>Translation</td></tr> 
```

2020-11-02 18:50 UTC, samfundev commented on HTML/Baybayin Words.html
> +			   <tr><td>ginto</td><td>gold</td><td>langoy</td><td>swim</td><td>plato</td><td>plate</td></tr>
```suggestion
               <tr><td>bahay</td><td>house</td><td>kapitan</td><td>captain</td><td>tanso</td><td>copper</td></tr>
               <tr><td>pagkain</td><td>food</td><td>palakpak</td><td>clap</td><td>pilak</td><td>silver</td><tr>
               <tr><td>tulog</td><td>sleep</td><td>mata</td><td>eyes</td><td>patay</td><td>dead</td></tr>
               <tr><td>tulay</td><td>bridge</td><td>sisid</td><td>dive</td><td>bingi</td><td>deaf</td></tr>
               <tr><td> kahoy</td><td>wood</td><td>halaman</td><td>plant</td><td>bulag</td><td>blind</td></tr>
               <tr><td>asukal</td><td>sugar</td><td>gamot</td><td>medicine</td><td>pilay</td><td>lame</td></tr>
               <tr><td>mayaman</td><td>rich</td><td>isla</td><td>island</td><td>pipi</td><td>mute</td></tr>
               <tr><td>sapatos</td><td>shoe</td><td>tago</td><td>hide</td><td>mantsa</td><td>stain</td></tr>
               <tr><td>ginto</td><td>gold</td><td>langoy</td><td>swim</td><td>plato</td><td>plate</td></tr>
```

2020-11-02 18:50 UTC, samfundev commented on HTML/Baybayin Words.html
> +			   </table>
```suggestion
               <tr><td>kayamanan</td><td>treasure</td><td>kidlat</td><td>lightning</td><td>kuwintas</td><td>necklace</td></tr>
               <tr><td> mahina</td><td>weak</td><td>hapunan</td><td>dinner</td><td>singsing</td><td>ring</td></tr>
               <tr><td> bayabas</td><td>guava</td><td>agahan</td><td>breakfast</td><td>hinto</td><td>stop</td></tr>
               </table>
```

2020-11-03 17:23 UTC, MrPeanut1028 commented
Still need to update the HTML with Sam's suggested changes and the lining up, as well as the SVG Minification.

2020-11-03 17:51 UTC, MrPeanut1028 requested changes

2020-11-03 17:51 UTC, MrPeanut1028 commented on HTML/Baybayin Words.html
> +</head>
Copy over the header from the template, this isn't the correct one (plus the spacing on line 8 is off.

2020-11-03 17:51 UTC, MrPeanut1028 commented on HTML/Baybayin Words.html
> +        </div>
I believe there's an extra closing tag here.

2020-11-03 19:14 UTC, MrPeanut1028 commented on HTML/Baybayin Words.html
> +    <title>Module Name — Keep Talking and Nobody Explodes Module</title>
Need the module name in the header, not `Module Name`.

2020-11-03 19:33 UTC, MrPeanut1028 approved these changes

2020-11-03 19:33 UTC, merged