Add a bunch of stuff.
Timwi/KtaneContent pull request #835
Opened 2020-11-16 16:46 UTC by Mirage-Xel

-Add the following modules:
Snack Attack
Security Council
Jackbox.TV
Johnson Solids
The Close Button
-Add White Arrows' icon.
-Fix Bigrgunch22 Being credited as CrunchyBot in two modules.

2020-11-16 18:02 UTC, samfundev requested changes
I found 2 problems running this PR through the linter.

2020-11-16 18:02 UTC, samfundev commented on HTML/img/Component/Musical Transposition.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 348 348" fill="none"><path d="M5.079 5.776h336.913v337.67H5.08z" stroke-width="2" stroke="#000"/><path d="M282.734 40.554c0-8.376 6.966-15.165 15.
\<text\> elements should be converted to <path> elements.

2020-11-16 18:02 UTC, samfundev commented on HTML/img/Component/The Close Button.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Component SVGs should be minified with SVGOMG.

2020-11-23 05:59 UTC, MrPeanut1028 requested changes
There's a ton of merge conflicts as well as a lot of `.meta` files, that'll need to be removed / fixed. Based on the number of fixes that need to be made here, Rdzanu's PR will probably be merged before yours, so it'd be worth making sure you two both didn't make the same changes.

2020-12-06 02:46 UTC, closed without merging